### ISSUE TITLE
Pas file missing

### ISSUE THREAD

**Issue by limelect** [landgraf-dev/openapi-delphi-generator#1]
Bcl.Code.MetaClasses  missing
 Bcl.Logging,
  Bcl.Code.MetaClasses,
  Bcl.Code.DelphiGenerator,
  OpenAPI.Classes,
  OpenAPI.Classes.Path,
  OpenAPI.Classes.Operation,
  OpenAPI.Classes.Parameter,
  OpenAPI.Document,
  OpenAPI.Types,
  XData.JSchema.Classes,

Any more?

**Comment by wlandgraf** [comment]
Those are units from [TMS BIZ](https://www.tmssoftware.com/site/tmsbizintro.asp). You have to install it, either registered or trial version.
Note that you only need it to rebuild the OpenApi Delphi Generator tool. Those are not needed to compile the generated client.
You can simply download the compiled Open Api Delphi Generator executable file and use it.
