### ISSUE TITLE
EJsonExpectedValue exception on local .json file

### ISSUE THREAD

**Issue by rhmskerk** [landgraf-dev/openapi-delphi-generator#10]
Using a local file as input I get:
Exception: Cannot retrieve OpenApi version - Value expected but invalid character found at $ (EJsonExpectedValue)
The file was saved in Windows, and does not contain leading UTF-8 characters
If I change the file and insert 3 blanks at the start, it works fine.

Debugging in Delphi, in OpenApiGen.Main, function GetOpenApiVersion, I see the value of "Content" being
wagger":"2.0"...

**proposed change to unit OpenApiGen.Main**
function LoadContent(const Source: string; Options: TBuilderOptions): string;
var
  Uri: IUri;
begin
  if StartsText('http://', Source) or StartsText('https://', Source) then
  begin
    Result := LoadHttpContent(Source);
    Uri := TUri.Create(Source);
    if Options.DocumentUrl = '' then
      Options.DocumentUrl := Uri.Scheme + '://' + Uri.Authority;
  end
  else
  **begin**
    Result := trim(TFile.ReadAllText(Source, TEncoding.UTF8));
    **if (Result <> '') and (Result[1] <> '{') then
      Result := trim(TFile.ReadAllText(Source));
  end;**
end;

**Comment by wlandgraf** [comment]
Can you please provide the exact file you used and raised the error?
I cannot reproduce it, files with leading spaces parse fine here.

I'd rather investigate what exactly is going on instead of just throwing a `Trim` there. The parser should be handling that.

**Comment by rhmskerk** [comment]
It has to do with leading encoding characters in the text-file

Met vriendelijke groet,

Rob Heemskerk
Allround Services Int. BV


Op ma 25 sep 2023 om 14:45 schreef wlandgraf ***@***.***>:

**Comment by rhmskerk** [comment]
Sorry, i see the attachment in the mail did not come through...
[Qualiview.json.txt](https://github.com/landgraf-dev/openapi-delphi-generator/files/12725394/Qualiview.json.txt)

**Comment by wlandgraf** [comment]
Cannot reproduce. That files is read fine by the generator.

**Comment by rhmskerk** [comment]
It's not really the generator, it's the call to TFiles.ReadAllText(Source, TEncoding.UTF8) that doesn't handle all text-files correctly. I am using Delphi 10.0.
I've attached the file in a zip, so you really get the original file.
[Qualiview.zip](https://github.com/landgraf-dev/openapi-delphi-generator/files/12735340/Qualiview.zip)

**Comment by wlandgraf** [comment]
What does `TFiles.ReadAllText` has to do with the generator?

**Comment by rhmskerk** [comment]
sorry, TFile.ReadAllText
unit OpenApiGen.Main;, line 68

**Comment by wlandgraf** [comment]
Can you please provide the **exact** steps to reproduce the issue?
I tried to import the mentioned file using the command-line, and it works fine.

**Comment by rhmskerk** [comment]
I downloaded the source and compiled it using delphi 10.0 on Windows Server
standard Debug configuration, 32-bit Windows platform
Then I run it from within Delphi with parameters
-i:"D:\Asi\Documentatie\Rom\Qualiview.json" -o:"d:\Qualiview" -n:QualiviewApi -m:MultipleClientsFromFirstTagAndOperationId

on Line 68 of OpenApiGen,Main
    Result := TFile.ReadAllText(Source, TEncoding.UTF8);
 I can see that the result lacks the first view bytes and starts with **wagger":"2.0"**

following that i get the EJsonExpectedValue

**Comment by wlandgraf** [comment]
What can I say? Maybe it's a Delphi 10 bug. The executable is compiled with Delphi 11, and it works fine.
I have updated the binary in the Releases, you can download the latest release and try with it.

https://github.com/landgraf-dev/openapi-delphi-generator/releases/tag/v1.1.4
