### ISSUE TITLE
F2069: Line too long (more than 1023 characters)

### ISSUE THREAD

**Issue by jdredd87** [landgraf-dev/openapi-delphi-generator#12]
Importing https://developer.ebay.com/api-docs/master/sell/feed/openapi/3/sell_feed_v1_oas3.json

Has huge comment.  Maybe can try and break them up? 

Delphi 11.3

    /// The value of the <strong>limit</strong> parameter submitted in the request, which is the maximum number of schedule templates to return per page, from the result set. A result set is the complete set of schedule templates returned by the method. <p> <span class="tablenote"><strong>Note:</strong> Though this parameter is not required to be submitted in the request, the parameter defaults to 10 if omitted.</span></p><p> <span class="tablenote"><strong>Note:</strong> If this is the last or only page of the result set, the page may contain fewer tasks than the <strong>limit</strong> value. To determine the number of pages in a result set, divide the total value (total number of tasks matching input criteria) by this limit value, and then round up to the next integer. For example, if the <strong>total</strong> value was <code>120</code> (120 total tasks) and the <strong>limit</strong> value was <code>50</code> (show 50 tasks per page), the total number of pages in the result set is three, so the seller would have to make three separate <strong>getScheduleTemplates</strong> calls to view all tasks matching the input criteria.</span></p>

**Comment by wlandgraf** [comment]
Importing such file works fine here with latest version, 1.1.5. 
Can you please check?

**Comment by wlandgraf** [comment]
Here is the command-line used (I renamed the file to `testapi.json` and put it in the `C:\temp` folder:

```
OpenApiDelphiGen -i:"C:\temp\testapi.json" -o:"C:\temp\Delphi\test" -n:testapi -m:MultipleClientsFromFirstTagAndOperationId
```
