### ISSUE TITLE
Please clear up: May code generated by OpenAPI Client Generator for Delphi be used commercially?

### ISSUE THREAD

**Issue by yonojoy** [landgraf-dev/openapi-delphi-generator#13]
To compile the code generated by this project the files in the Dist folder are necessary.
This project is licensed under the [Apache 2.0 with Commons Clause License](https://github.com/landgraf-dev/openapi-delphi-generator/blob/main/LICENSE) which forbids to sell the software generated by the code.
This means IMHO, that the generated code may not be use commercially.

Is this your intention?

If yes, you should place a clear statement on the project page to hint at this issue.
If no, you should license the files in the Dist folder under a more permissive license (eg. Apache 2.0 License).

**Comment by wlandgraf** [comment]
Apache 2.0 with Commons Clause License is not that restrictive. You still can use the code in commercial software.
What you can't do is the "Sell" the software, i.e, the code itself and its functionalities.

For example, you cannot create your own Open API Generator based on this code and sell it yourself.
About the generated code, it means indeed that you cannot for example create a library to connect to API Foo and then sell that software just for the sole purpose of connecting to API Foo. That doesn't prevent you from using the generated code that connects to API Foo and embed it in your commercial application that has other features.

**Comment by yonojoy** [comment]
Sorry for causing confusion. You are right. I read the license text again:

The right to monetarize the code is forbidden "[for] a product or service **whose value derives, entirely or substantially**, from the functionality of the Software."
