### ISSUE TITLE
Handling of Double data type seems not to be correct

### ISSUE THREAD

**Issue by yonojoy** [landgraf-dev/openapi-delphi-generator#14]
Given a OpenAPI parameter like this:

          {
            "name": "fee",
            "in": "query",
            "description": "",
            "required": false,
            "type": "number"
          }

the generated code uses the Double data type for `Fee`. This is than called in the following way:

    Request.AddQueryParam('fee', Fee);

with 

    procedure AddQueryParam(const Name, Value: string);

This does not seem to be correct. The code should not rely on implicit conversion as this will use the system locale.
At least in XE4 this wont even compile.

A resolution would be to have an explicit conversion.

**Comment by wlandgraf** [comment]
Fixed in 795688a7dc41f8a09f399cf589855ff385b4ba87

**Comment by yonojoy** [comment]
The fix https://github.com/landgraf-dev/openapi-delphi-generator/commit/795688a7dc41f8a09f399cf589855ff385b4ba87 generates different code for Double params. Instead of

    Request.AddQueryParam('fee', Fee);

the new generated code will read:
  
    Request.AddQueryParam('fee', DoubleToParam(Fee));

So my already generated (and modified) code had to be adopted manually. But I think, I will be the only one affected. It is the correct way, to fix the problem.

**Comment by wlandgraf** [comment]
Yes, it followed the same convention as parameters of type Integer or TDateTime. The conversion should happen in the generated code, it's not the job of `AddQueryParam` to do type conversion.
