### ISSUE TITLE
Support for older Delphi versions (at least from XE4)

### ISSUE THREAD

**Issue by yonojoy** [landgraf-dev/openapi-delphi-generator#16]
At the moment Delphi XE8 or better is required for the generated code to run.

With existing support for Indy it is not too difficult to support older Delphi versions as well.

**Comment by yonojoy** [comment]
I implemented this in pull request #17, because we internally still use XE4 (maybe the code will work for older Delphi version too, but I did not test this).

Two things needed to be changed: Indy needed to be used by default and TJsonWrapper had to be adapted, because in XE4 JSON may only be parsed via Data.DBXJSON.
I decided to split up TJsonWrapper in separate classes, because I did not want to spread more IFDEFS and the classes are trivial in my opinion.

My XE4 version is up and running. But please be careful, the code for XE8+ and for FPC is completely untested.

**Comment by wlandgraf** [comment]
Thank you for the contribution. Just one small remark:

>I decided to split up TJsonWrapper in separate classes, because I did not want to spread more IFDEFS and the classes are trivial in my opinion.

I saw that, and I respectfully disagree. Would it possible for you to modify the pull request to keep the original single unit and just add the directives?

**Comment by yonojoy** [comment]
Could you please read my explanation in pull request #17 and judge again.

**Comment by wlandgraf** [comment]
Done.

**Comment by wlandgraf** [comment]
Support added in commit 5fd5cb17796be12f967c6b1a82ee1df6600c7062
