### ISSUE TITLE
No Overloaded Version Error

### ISSUE THREAD

**Issue by cihadkocasahan** [landgraf-dev/openapi-delphi-generator#19]
Hi, I encountered an error while compiling OpenApi250.bpl at the line FValues.AddPair(AName, AValue.Value);. The issue was resolved when I replaced it with FValues.AddPair(TJSONPair.Create(AName, AValue.Value.ToString));.

**Comment by wlandgraf** [comment]
Sorry, but how do you "compile OpenApi250.bpl"? You can't compile a BPL. And if you are referring a dproj/dpk. there is no such file in this project.

**Comment by cihadkocasahan** [comment]
Oh sorry,I wrote to the wrong project.Thank you for answer.
