### ISSUE TITLE
Missing JSON schema type

### ISSUE THREAD

**Issue by Pecaas** [landgraf-dev/openapi-delphi-generator#21]
When called attached schema it raises exception EJSchemaReaderException: Missing JSON schema type at $.paths./messages/{folder}.get.parameters[0].schema (all versions)

[openapi3_0.json](https://github.com/landgraf-dev/openapi-delphi-generator/files/13197792/openapi3_0.json)
[openapi.json](https://github.com/landgraf-dev/openapi-delphi-generator/files/13197793/openapi.json)

**Comment by wlandgraf** [comment]
Correct, the first parameter of `/messages/{folder}` endpoint doesn't have a type specified:

```json
    "/messages/{folder}/{id_from}/{id_to}": {
      "delete": {
        "tags": [
          "Modify"
        ],
        "summary": "Delete messages",
        "description": "Delete specified messages from the chosen folder. Not entering any ID's will delete all messages.",
        "operationId": "Messages::messages_delete",
        "parameters": [
          {
            "name": "folder",
            "in": "path",
            "description": "Folder's name to delete messages from.",
            "required": true,
            "schema": {
              "enum": [
                "inbox",
                "outbox",
                "sent"
              ]
            }
          },
```

Note the `schema` object. It should have a property `"type": "string"`.

**Comment by Pecaas** [comment]
I am not sure what I have to do to correct it. Schema is downloaded form https://www.smseagle.eu/docs/apiv2/

**Comment by wlandgraf** [comment]
Modify the JSON to include the `type` property:

```json
            "schema": {
              "type": "string",
              "enum": [
                "inbox",
                "outbox",
                "sent"
              ]
            }
```
