### ISSUE TITLE
Access violation with OpenAPI 3.0.0

### ISSUE THREAD

**Issue by AliDehbansiahkarbon** [landgraf-dev/openapi-delphi-generator#24]
I got an access violation exception when I tried with an OpenAPi 3.0 Specification(File and URL).
After attempting to compile using a trial version of TMS, I discovered that the issue lies in the line where TAnalyzer.Analyze(Document) is called.
I'm not sure but it could be a bug in the TMS library.

**Comment by AliDehbansiahkarbon** [comment]
I got an access violation exception when I tried with an OpenAPi 3.0 Specification(File and URL).
After attempting to compile using a trial version of TMS, I discovered that the issue lies in the line where TAnalyzer.Analyze(Document) is called.
I'm not sure but it could be a bug in the TMS library.

**Comment by wlandgraf** [comment]
Please provide the file you are trying to import so we can reproduce the problem as well.

**Comment by AliDehbansiahkarbon** [comment]
[response.json](https://github.com/landgraf-dev/openapi-delphi-generator/files/13501302/response.json)
