### ISSUE TITLE
Add ability for Logging

### ISSUE THREAD

**Issue by yonojoy** [landgraf-dev/openapi-delphi-generator#27]
There should exist an lightweight option to add logging for requests and responses.

I would like to be able to add a logging class like this to do my logging for debugging purposes:

    type
        TIOpenApiRestLogger = class(TInterfacedObject, IRestLogger)
        private
            FLogDir: string;
            function GetLogFileName(AMethod, AUrl: string; ALogId: string; APrefix: string = ''): string;
            function GetContentInfo(AMethod, AUrl: string): string;
        protected   //access via interface
            function LogRequest(AMethod: string; AUrl: string; ARequestBody: TStringStream): string;
            procedure LogResponse(AMethod: string; AUrl: string; ALogId: string; AResponse: IRestResponse);
        public
            constructor Create(ALogDir: string);
        end;

    constructor TIOpenApiRestLogger.Create(ALogDir: string);
    begin
        if ALogDir <> '' then
        begin
            ForceDirectories(ALogDir);
            FLogDir := MakePathStr(ALogDir);
        end;
    end;

    /// LogId is used to match request to response
    function TIOpenApiRestLogger.GetLogFileName(AMethod, AUrl: string; ALogId: string; APrefix: string = ''): string;
    var
        Path: string;
    begin
        Path := ExtractUrlPath(AUrl);
        Result := FLogDir + APrefix + AMethod + '.'
          + StrToFileName(Path, REPLACE_SPACES_YES) + '.' + ALogId + '.txt';
    end;

    function TIOpenApiRestLogger.GetContentInfo(AMethod, AUrl: string): string;
    begin
        Result := '---' + #13#10;        //YAML frontmatter format
        Result := Result + 'Method: ' + AMethod + #13#10;
        Result := Result + 'Url: ' + AUrl + #13#10;
    end;

    function TIOpenApiRestLogger.LogRequest(AMethod, AUrl: string; ARequestBody: TStringStream): string;
    var
        ToLog: string;
    begin
        Result := GuidToBase64(GenerateTGuid());
        if FLogDir <> '' then
        begin
            ToLog := GetContentInfo(AMethod, AUrl);
            ToLog := ToLog + '---' + #13#10;
            if Assigned(ARequestBody) then
              ToLog := ToLog + ARequestBody.DataString;

            StrToFile(GetLogFileName(AMethod, AUrl, Result, 'REQ.'), ToLog, TEncoding.UTF8);
        end;
    end;

    procedure TIOpenApiRestLogger.LogResponse(AMethod, AUrl, ALogId: string; AResponse: IRestResponse);
    var
        ToLog: string;

        function HeaderInfo(AHeaderName: string): string;
        begin
            Result := '  ' + AHeaderName + ': ' + AResponse.GetHeader(AHeaderName) + #13#10;
        end;

    begin
        Assert(Assigned(AResponse));
        //---
        if FLogDir <> '' then
        begin
            ToLog := GetContentInfo(AMethod, AUrl);
            ToLog := ToLog + 'StatusCode: ' + IntToStr(AResponse.StatusCode) + #13#10;
            ToLog := ToLog + 'Headers: ' + #13#10;
            ToLog := ToLog + HeaderInfo('Date');
            ToLog := ToLog + HeaderInfo('Content-Type');
            ToLog := ToLog + HeaderInfo('Content-Length');
            ToLog := ToLog + HeaderInfo('Connection');
            ToLog := ToLog + HeaderInfo('Vary');
            ToLog := ToLog + HeaderInfo('Allow');
            ToLog := ToLog + '---' + #13#10;
            ToLog := ToLog + AResponse.ContentAsString;

            StrToFile(GetLogFileName(AMethod, AUrl, ALogId, 'RESP.'), ToLog, TEncoding.UTF8);
        end;
    end;

**Comment by yonojoy** [comment]
@wlandgraf  Could you please have a look at https://github.com/landgraf-dev/openapi-delphi-generator/commit/ac644604b4208f979a83aecd83bde426446c8032 . This is my proposal to add logging capabilities to your OpenApi calls. With this extension one can write a class (see above), that does handle the logging.

If you like this proposal I would adapt this code to your latest commit (63616434fa5120e8118071190f13aac1722f15cf) and provide a pull request.

**Comment by wlandgraf** [comment]
@yonojoy Yes, I think it's a nice addition. I'd appreciate if you could provide the pull request based on latest code.

**Comment by yonojoy** [comment]
I provided pull request #29 for this. 

To use this you have to provide a class, that implements `IRestLogger` (like the one above). 
Then you need to add this implementation to your rest configuration via `IRestConfig.SetLogger`.

With the code above for instance following file is created for a reponse:

    ---
    Method: GET
    Url: https://api.xxxtests.com/v1/management/branches/?hash=60ddedc3-e146-433b-8220-4bbf228df28b
    StatusCode: 200
    Headers: 
      Date: Thu, 08 Feb 2024 19:14:33 GMT
      Content-Type: application/json
      Content-Length: 148
      Connection: keep-alive
      Vary: Accept, Accept-Language, Authorization, Origin
      Allow: GET, POST, HEAD, OPTIONS
    ---
    [{"id":1326,"supported_types":["1","2","3","4"],"name":"Test","logo_file":null}]

**Comment by wlandgraf** [comment]
Merged
