### ISSUE TITLE
Incomplete import OpenApi V3.0.1

### ISSUE THREAD

**Issue by mborgues** [landgraf-dev/openapi-delphi-generator#6]
When importing an OpenApi V3.0.1 json, the methods corresponding to the routes are not created as in the example available in the OpenApi 2.0 version
[swagger.zip](https://github.com/landgraf-dev/openapi-delphi-generator/files/11050620/swagger.zip)

**Comment by wlandgraf** [comment]
Can you please provide more details about how you are trying to import it? 
We tried it here and we get this error:

```
OpenApi Client Generator for Delphi version 1.1.1
Copyright (c) Landgraf.dev - all rights reserved.

Exception: Cannot determine the URL of the API spe, please provide it using DocumentUrl param
```

**Comment by ehaesevoets** [comment]
Hi, I have encountered the reference issue as well. The reference is not inserted and the following error appears:

> Project OpenApiDelphiGen.exe raised exception class EConvertError with message ''#/components/parameters/format' is not a valid floating point value'.

[openapi.zip](https://github.com/landgraf-dev/openapi-delphi-generator/files/11514568/openapi.zip)

When the "$ref": "#/components/parameters/format" is replaced by what can be found in the reference it continues and then the next error will appear.

> Project OpenApiDelphiGen.exe raised exception class EJSchemaReaderException with message 'Missing JSON schema type at $.paths./issues.{format}.get.responses.200.content.application/json.schema.properties.issues.items'.

It could be that the "allOf" parameter is not recognized?

I also included a zip file with the json and the yaml file, the yaml file was converted to json via the swagger editor.
The yaml file can also be downloaded from [https://d-yoshi.github.io/redmine-openapi/](url)

I think this one is a challenge to get converted but on the other hand could be a good test as well ;-)

**Comment by wlandgraf** [comment]
Indeed, `allOf` keyword is unfortunately not supported.

**Comment by JohanDeRidder** [comment]
I have the same problem, can you add the "allOf keyword" functionality?

With kind regards, 
Johan de Ridder

**Comment by wlandgraf** [comment]
See #22
