### ISSUE TITLE
Adding a GUI over the CLI

### ISSUE THREAD

**Issue by DeveloppeurPascal** [landgraf-dev/openapi-delphi-generator#7]
I'd like to add a simple FMX GUI for calling the command, do you think it could be interesting as a PULL REQUEST (with a "source-gui" folder) in the project or as a new repository ?

**Comment by wlandgraf** [comment]
Hi @DeveloppeurPascal.
Sure, you can send a pull request, indeed, please include it in a separated folder. Thank you.

**Comment by DeveloppeurPascal** [comment]
I'll do that soon.
